# 📝 Catatan Penting
- Sebelum mengerjakan assignment ini, harap terlebih dahulu membuat salinan notebook dengan memilih menu `File → Save a Copy in Drive`.
- Gunakan salinan notebook tersebut untuk menuliskan seluruh jawaban Anda. Tips pengerjaan:
  - **Baca instruksi dengan teliti**. Pastikan memahami apa yang diminta.
  - Lengkapi semua soal dalam Jupyter notebook ini. Test kode & validasi secara bertahap.
  - **Berikan komentar**. Jelaskan pendekatan dan logika Anda.
  - **Manfaatkan dokumentasi pandas**. Jangan ragu mencari referensi!
- Sesuai dengan ketentuan pengerjaan assignment, **diharapkan peserta tidak sepenuhnya mengandalkan bantuan AI dalam menyelesaikan tugas ini**.
- ## ‼️‼️PENTING: **Share dengan setting "anyone with the link" lalu paste url ke LMS agar mudah dibuka**

# Data Manipulation Assignment Answer
by `<< Isi Nama Disini >>`

**Dibimbing - Batch 12 | DE**



## Deskripsi Dataset
Anda akan bekerja dengan **Dataset Analitik Pelanggan E-commerce** yang berisi:
- **Customers**: Data demografi dan segmen pelanggan
- **Products**: Katalog produk dengan kategori dan harga
- **Orders**: Riwayat transaksi dengan timestamp
- **Sessions**: Data sesi website dengan metrik konversi

---

## 📋 Setup Tugas

- **Instruksi**: Jalankan cell setup di bawah ini untuk menghasilkan dataset.
- ## **‼️‼️DILARANG MENGUBAH CODE PADA SECTION INI**

In [ ]:
# SETUP CELL - ‼️JANGAN DIUBAH‼️
# Jalankan cell ini terlebih dahulu untuk menghasilkan dataset tugas

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Set random seed untuk reproducibility
np.random.seed(42)

print(">>> Menghasilkan dataset tugas...")

# 1. Generate Dataset Customers
def generate_customers(n=800):
    customer_data = {
        'customer_id': range(1, n+1),
        'nama_depan': np.random.choice(['Andi', 'Sari', 'Budi', 'Dewi', 'Rizki', 'Maya', 'Doni', 'Fitri'], n),
        'nama_belakang': np.random.choice(['Pratama', 'Wijaya', 'Santoso', 'Putri', 'Kusuma', 'Sari', 'Nugroho'], n),
        'umur': np.random.normal(35, 12, n).astype(int).clip(18, 65),
        'jenis_kelamin': np.random.choice(['L', 'P'], n),
        'email_domain': np.random.choice(['gmail.com', 'yahoo.com', 'outlook.com', 'perusahaan.com'], n, p=[0.4, 0.25, 0.25, 0.1]),
        'kota': np.random.choice(['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar'], n),
        'segmen_pelanggan': np.random.choice(['Premium', 'Standard', 'Basic'], n, p=[0.2, 0.5, 0.3]),
        'tanggal_daftar': pd.date_range('2023-01-01', '2024-12-31', periods=n)
    }
    df = pd.DataFrame(customer_data)
    df['email'] = df['nama_depan'].str.lower() + '.' + df['nama_belakang'].str.lower() + '@' + df['email_domain']
    df['nama_lengkap'] = df['nama_depan'] + ' ' + df['nama_belakang']
    return df[['customer_id', 'nama_lengkap', 'umur', 'jenis_kelamin', 'email', 'kota', 'segmen_pelanggan', 'tanggal_daftar']]

# 2. Generate Dataset Products
def generate_products(n=150):
    kategori = ['Elektronik', 'Pakaian', 'Buku', 'Olahraga', 'Rumah Tangga', 'Kecantikan']
    merek = ['MerekA', 'MerekB', 'MerekC', 'MerekD', 'MerekE']

    product_data = {
        'product_id': range(1, n+1),
        'nama_produk': [f'Produk_{i}' for i in range(1, n+1)],
        'kategori': np.random.choice(kategori, n),
        'merek': np.random.choice(merek, n),
        'harga': np.random.lognormal(3, 0.8, n).round(0),
    }

    df = pd.DataFrame(product_data)
    df['biaya'] = (df['harga'] * np.random.uniform(0.4, 0.7, len(df))).round(0)
    df['margin_keuntungan'] = ((df['harga'] - df['biaya']) / df['harga'] * 100).round(2)
    return df

# 3. Generate Dataset Orders
def generate_orders(customers_df, products_df, n=2000):
    order_data = {
        'order_id': range(1, n+1),
        'customer_id': np.random.choice(customers_df['customer_id'], n),
        'product_id': np.random.choice(products_df['product_id'], n),
        'jumlah': np.random.choice([1, 2, 3, 4, 5], n, p=[0.5, 0.25, 0.15, 0.07, 0.03]),
        'tanggal_order': pd.date_range('2024-01-01', '2024-12-31', periods=n),
        'status': np.random.choice(['Selesai', 'Pending', 'Dibatalkan'], n, p=[0.85, 0.1, 0.05])
    }
    return pd.DataFrame(order_data)

# 4. Generate Dataset Sessions
def generate_sessions(customers_df, n=3000):
    session_data = {
        'session_id': range(1, n+1),
        'customer_id': np.random.choice(customers_df['customer_id'], n),
        'waktu_mulai_sesi': pd.date_range('2024-01-01', '2024-12-31', periods=n),
        'halaman_dilihat': np.random.poisson(5, n) + 1,
        'durasi_sesi_menit': np.random.exponential(15, n).round(1),
        'tipe_device': np.random.choice(['Desktop', 'Mobile', 'Tablet'], n, p=[0.5, 0.4, 0.1]),
        'konversi': np.random.choice([True, False], n, p=[0.15, 0.85])
    }
    df = pd.DataFrame(session_data)
    df['bounce_rate'] = (df['halaman_dilihat'] == 1).astype(int)
    return df

# Generate semua dataset
customers_df = generate_customers(800)
products_df = generate_products(150)
orders_df = generate_orders(customers_df, products_df, 2000)
sessions_df = generate_sessions(customers_df, 3000)

print("Pembuatan dataset selesai!")
print(f"-- Customers: {len(customers_df)} baris")
print(f"-- Products: {len(products_df)} baris")
print(f"-- Orders: {len(orders_df)} baris")
print(f"-- Sessions: {len(sessions_df)} baris")
print("\nSiap memulai tugas Anda!")

>>> Menghasilkan dataset tugas...
Pembuatan dataset selesai!
-- Customers: 800 baris
-- Products: 150 baris
-- Orders: 2000 baris
-- Sessions: 3000 baris

Siap memulai tugas Anda!

---

# 🎯 Soal 1: Eksplorasi Data dan Filtering
## Analisis Data Pelanggan Jakarta Premium
Temukan semua pelanggan dari kota Jakarta yang berada dalam segmen Premium dan berumur antara 25-40 tahun. Tampilkan informasi lengkap mereka dan hitung berapa total pelanggan yang memenuhi kriteria tersebut.

In [ ]:
# Soal 1: Analisis Data Pelanggan Jakarta Premium
# TODO: Filter pelanggan berdasarkan multiple kondisi

# Langkah 1: Tampilkan informasi dasar dataset customers
print("=== INFORMASI DATASET CUSTOMERS ===")
# Tampilkan shape, kolom, dan 5 baris pertama
# Kode Anda di sini
print(f"Shape = {customers_df.shape}")
print(f"\nKolom = {customers_df.columns}")
print(f"\n{customers_df.head(5)}")

# Langkah 2: Filter pelanggan sesuai kriteria
pelanggan_jakarta_premium = None  # Kode filtering Anda di sini

print("\n=== HASIL FILTERING ===")
print("Pelanggan Premium dari Jakarta (umur 25-40 tahun):")
pelanggan_jakarta_premium = customers_df.loc[(customers_df['kota']== 'Jakarta') & (customers_df['segmen_pelanggan'] == 'Premium') & (customers_df['umur'].between(25,40)) ]
print(pelanggan_jakarta_premium)
# Tampilkan hasil dan total jumlah
print(f"\nJumlah pelanggan yang memenuhi kriteria = {len(pelanggan_jakarta_premium)}")

=== INFORMASI DATASET CUSTOMERS ===
Shape = (800, 8)

Kolom = Index(['customer_id', 'nama_lengkap', 'umur', 'jenis_kelamin', 'email', 'kota',
       'segmen_pelanggan', 'tanggal_daftar'],
      dtype='object')

   customer_id   nama_lengkap  umur jenis_kelamin                    email  \
0            1   Doni Pratama    25             P   doni.pratama@yahoo.com
1            2      Dewi Sari    33             L      dewi.sari@yahoo.com
2            3  Rizki Pratama    35             L  rizki.pratama@gmail.com
3            4   Doni Pratama    36             P   doni.pratama@gmail.com
4            5      Budi Sari    26             L      budi.sari@gmail.com

       kota segmen_pelanggan                tanggal_daftar
0  Surabaya          Premium 2023-01-01 00:00:00.000000000
1   Jakarta            Basic 2023-01-01 21:55:38.673341677
2  Surabaya            Basic 2023-01-02 19:51:17.346683354
3  Semarang         Standard 2023-01-03 17:46:56.020025031
4   Bandung            Basic 2023-01-04 15:42:34.693366708

=== HASIL FILTERING ===
Pelanggan Premium dari Jakarta (umur 25-40 tahun):
     customer_id  nama_lengkap  umur jenis_kelamin  \
27            28   Sari Kusuma    25             L
102          103     Sari Sari    30             P
171          172  Rizki Wijaya    25             P
183          184  Budi Pratama    32             L
299          300  Fitri Wijaya    38             L
322          323   Dewi Wijaya    39             P
333          334   Budi Kusuma    35             L
373          374  Fitri Wijaya    33             L
529          530    Sari Putri    37             P
582          583  Dewi Pratama    27             P
610          611  Rizki Kusuma    35             L
634          635    Sari Putri    30             L
641          642  Maya Nugroho    32             L
743          744    Rizki Sari    29             P

                           email     kota segmen_pelanggan  \
27    sari.kusuma@perusahaan.com  Jakarta          Premium
102        sari.sari@outlook.com  Jakarta          Premium
171       rizki.wijaya@gmail.com  Jakarta          Premium
183  budi.pratama@perusahaan.com  Jakarta          Premium
299  fitri.wijaya@perusahaan.com  Jakarta          Premium
322        dewi.wijaya@gmail.com  Jakarta          Premium
333      budi.kusuma@outlook.com  Jakarta          Premium
373       fitri.wijaya@gmail.com  Jakarta          Premium
529       sari.putri@outlook.com  Jakarta          Premium
582       dewi.pratama@gmail.com  Jakarta          Premium
610       rizki.kusuma@yahoo.com  Jakarta          Premium
634         sari.putri@gmail.com  Jakarta          Premium
641       maya.nugroho@yahoo.com  Jakarta          Premium
743         rizki.sari@gmail.com  Jakarta          Premium

                   tanggal_daftar
27  2023-01-25 16:02:24.180225281
102 2023-04-04 04:35:44.680851064
171 2023-06-06 05:35:13.141426784
183 2023-06-17 04:42:57.221526908
299 2023-10-01 04:17:43.329161452
322 2023-10-22 04:37:32.816020024
333 2023-11-01 05:49:38.222778472
373 2023-12-07 18:55:25.156445556
529 2024-04-28 07:35:58.197747184
582 2024-06-15 17:45:07.884856072
610 2024-07-11 07:43:10.738423024
634 2024-08-02 05:58:38.898623280
641 2024-08-08 15:28:09.612015016
743 2024-11-09 20:03:54.292866080

Jumlah pelanggan yang memenuhi kriteria = 14

In [ ]:
pelanggan_jakarta_premium

,customer_id,nama_lengkap,umur,jenis_kelamin,email,kota,segmen_pelanggan,tanggal_daftar
27,28,Sari Kusuma,25,L,sari.kusuma@perusahaan.com,Jakarta,Premium,2023-01-25 16:02:24.180225281
102,103,Sari Sari,30,P,sari.sari@outlook.com,Jakarta,Premium,2023-04-04 04:35:44.680851064
171,172,Rizki Wijaya,25,P,rizki.wijaya@gmail.com,Jakarta,Premium,2023-06-06 05:35:13.141426784
183,184,Budi Pratama,32,L,budi.pratama@perusahaan.com,Jakarta,Premium,2023-06-17 04:42:57.221526908
299,300,Fitri Wijaya,38,L,fitri.wijaya@perusahaan.com,Jakarta,Premium,2023-10-01 04:17:43.329161452
322,323,Dewi Wijaya,39,P,dewi.wijaya@gmail.com,Jakarta,Premium,2023-10-22 04:37:32.816020024
333,334,Budi Kusuma,35,L,budi.kusuma@outlook.com,Jakarta,Premium,2023-11-01 05:49:38.222778472
373,374,Fitri Wijaya,33,L,fitri.wijaya@gmail.com,Jakarta,Premium,2023-12-07 18:55:25.156445556
529,530,Sari Putri,37,P,sari.putri@outlook.com,Jakarta,Premium,2024-04-28 07:35:58.197747184
582,583,Dewi Pratama,27,P,dewi.pratama@gmail.com,Jakarta,Premium,2024-06-15 17:45:07.884856072
610,611,Rizki Kusuma,35,L,rizki.kusuma@yahoo.com,Jakarta,Premium,2024-07-11 07:43:10.738423024
634,635,Sari Putri,30,L,sari.putri@gmail.com,Jakarta,Premium,2024-08-02 05:58:38.898623280
641,642,Maya Nugroho,32,L,maya.nugroho@yahoo.com,Jakarta,Premium,2024-08-08 15:28:09.612015016
743,744,Rizki Sari,29,P,rizki.sari@gmail.com,Jakarta,Premium,2024-11-09 20:03:54.292866080

---

# 🎯 Soal 2: Operasi GroupBy dan Agregasi
## Analisis Pendapatan per Segmen Pelanggan
Hitung total pendapatan, rata-rata jumlah order, dan jumlah total order untuk setiap segmen pelanggan. Urutkan berdasarkan total pendapatan secara descending.

> **Petunjuk**: Anda perlu menggabungkan tabel orders dengan products untuk mendapatkan harga, kemudian dengan customers untuk mendapatkan segmen.

In [ ]:
# Soal 2: Analisis Pendapatan per Segmen Pelanggan
# TODO: Gabungkan orders dengan customers dan products, lalu group by segmen

# Langkah 1: Gabungkan tabel yang diperlukan
# Kode untuk merge orders, products, dan customers

# Langkah 2: Hitung total pendapatan per order
# Kode untuk menghitung revenue = harga * jumlah

# Langkah 3: Group by segmen dan hitung agregasi
analisis_segmen = None  # Kode groupby Anda di sini

print("Analisis pendapatan dan order berdasarkan segmen pelanggan:")
# Tampilkan hasil yang sudah diurutkan

Analisis pendapatan dan order berdasarkan segmen pelanggan:

In [ ]:
gabung = pd.merge(products_df, orders_df, on ="product_id", how = "left")
gabung

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,tanggal_order,status
0,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,458,30,1,2024-03-24 10:39:40.790395198,Selesai
1,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,600,725,2,2024-04-19 08:55:56.878439220,Selesai
2,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,621,508,1,2024-04-23 04:57:30.525262632,Selesai
3,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,672,17,1,2024-05-02 12:27:00.810405202,Dibatalkan
4,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,939,389,3,2024-06-20 06:29:42.891445724,Selesai
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1416,601,3,2024-09-15 08:48:01.440720360,Selesai
1996,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1513,17,4,2024-10-03 01:52:22.571285644,Selesai
1997,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1607,471,2,2024-10-20 05:47:56.038019012,Selesai
1998,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1789,460,1,2024-11-22 11:21:27.643821912,Selesai
1999,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1920,595,1,2024-12-16 09:25:28.964482240,Selesai

In [ ]:
gabung['revenue'] = gabung['harga'] * gabung['jumlah']
gabung

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,tanggal_order,status,revenue
0,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,458,30,1,2024-03-24 10:39:40.790395198,Selesai,17.0
1,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,600,725,2,2024-04-19 08:55:56.878439220,Selesai,34.0
2,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,621,508,1,2024-04-23 04:57:30.525262632,Selesai,17.0
3,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,672,17,1,2024-05-02 12:27:00.810405202,Dibatalkan,17.0
4,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,939,389,3,2024-06-20 06:29:42.891445724,Selesai,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1416,601,3,2024-09-15 08:48:01.440720360,Selesai,54.0
1996,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1513,17,4,2024-10-03 01:52:22.571285644,Selesai,72.0
1997,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1607,471,2,2024-10-20 05:47:56.038019012,Selesai,36.0
1998,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1789,460,1,2024-11-22 11:21:27.643821912,Selesai,18.0
1999,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1920,595,1,2024-12-16 09:25:28.964482240,Selesai,18.0

In [ ]:
df = pd.merge(gabung,customers_df, on = 'customer_id', how = "left")
df

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,tanggal_order,status,revenue,nama_lengkap,umur,jenis_kelamin,email,kota,segmen_pelanggan,tanggal_daftar
0,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,458,30,1,2024-03-24 10:39:40.790395198,Selesai,17.0,Dewi Santoso,35,P,dewi.santoso@gmail.com,Makassar,Standard,2023-01-27 11:53:41.526908635
1,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,600,725,2,2024-04-19 08:55:56.878439220,Selesai,34.0,Andi Santoso,38,L,andi.santoso@outlook.com,Jakarta,Basic,2024-10-23 11:26:39.499374216
2,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,621,508,1,2024-04-23 04:57:30.525262632,Selesai,17.0,Budi Sari,41,P,budi.sari@outlook.com,Bandung,Standard,2024-04-08 05:11:47.384230288
3,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,672,17,1,2024-05-02 12:27:00.810405202,Dibatalkan,17.0,Dewi Santoso,20,P,dewi.santoso@yahoo.com,Jakarta,Standard,2023-01-15 14:50:18.773466833
4,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,939,389,3,2024-06-20 06:29:42.891445724,Selesai,51.0,Andi Nugroho,51,P,andi.nugroho@gmail.com,Medan,Standard,2023-12-21 11:50:05.256570712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1416,601,3,2024-09-15 08:48:01.440720360,Selesai,54.0,Rizki Sari,23,L,rizki.sari@gmail.com,Makassar,Standard,2024-07-02 04:26:44.005006256
1996,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1513,17,4,2024-10-03 01:52:22.571285644,Selesai,72.0,Dewi Santoso,20,P,dewi.santoso@yahoo.com,Jakarta,Standard,2023-01-15 14:50:18.773466833
1997,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1607,471,2,2024-10-20 05:47:56.038019012,Selesai,36.0,Rizki Kusuma,41,P,rizki.kusuma@gmail.com,Medan,Premium,2024-03-05 09:52:56.470588232
1998,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1789,460,1,2024-11-22 11:21:27.643821912,Selesai,18.0,Budi Putri,40,L,budi.putri@perusahaan.com,Medan,Premium,2024-02-24 08:40:51.063829784
1999,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1920,595,1,2024-12-16 09:25:28.964482240,Selesai,18.0,Dewi Kusuma,43,P,dewi.kusuma@perusahaan.com,Jakarta,Standard,2024-06-26 16:52:51.964956192

In [ ]:
analisis_segmen = df.groupby('segmen_pelanggan', as_index= False).agg(
    total_revenue = ('revenue','sum'),
    rata2_revenue = ('revenue','mean'),
    transaksi_terbesar = ('revenue','max'),
    transaksi_terkecil = ('revenue','min'),
    banyaknya_transaksi = ('revenue','count')
).sort_values(by = 'total_revenue', ascending = False)

print("Analisis pendapatan dan order berdasarkan segmen pelanggan:")
# Tampilkan hasil yang sudah diurutkan

Analisis pendapatan dan order berdasarkan segmen pelanggan:

In [ ]:
analisis_segmen

,segmen_pelanggan,total_revenue,rata2_revenue,transaksi_terbesar,transaksi_terkecil,banyaknya_transaksi
2,Standard,50181.0,47.340566,435.0,2.0,1060
0,Basic,22400.0,45.901639,378.0,2.0,488
1,Premium,21100.0,46.681416,630.0,2.0,452

---

# 🎯 Soal 3: Feature Engineering dan Encoding
## Fitur Perilaku Pelanggan dan Encoding
Buat fitur perilaku pelanggan yang mencakup:
1. **Tenure pelanggan** (hari sejak pendaftaran)
2. **Rata-rata hari antar order** untuk setiap pelanggan
3. **Hari belanja favorit** (hari dalam seminggu paling sering order)
4. **Tier nilai pelanggan** berdasarkan total pengeluaran (High/Medium/Low)

Kemudian implementasikan encoding: one-hot encoding untuk kota

In [ ]:
# Soal 5: Fitur Perilaku Pelanggan dan Encoding
# TODO: Buat fitur perilaku dan implementasikan encoding

print("=== BAGIAN A: FEATURE ENGINEERING ===")

# Langkah 1: Hitung tenure pelanggan (hari sejak pendaftaran)
# Kode untuk menghitung hari dari tanggal_daftar sampai sekarang

# Langkah 2: Hitung rata-rata hari antar order per pelanggan
# Kode untuk menghitung interval antar order

# Langkah 3: Tentukan hari belanja favorit
# Kode untuk ekstrak hari dari tanggal_order dan cari yang paling sering

# Langkah 4: Buat tier nilai pelanggan berdasarkan total pengeluaran
# Kode untuk kategorisasi High/Medium/Low

print("\n=== BAGIAN B: ENCODING ===")

# Langkah 5: One-hot encoding untuk kota
# Kode untuk pd.get_dummies()

print("Contoh fitur perilaku pelanggan:")
# Tampilkan sample pelanggan dengan fitur-fitur baru

print("\nContoh hasil encoding:")
# Tampilkan contoh one-hot encoding kota

In [ ]:
df.columns

Index(['product_id', 'nama_produk', 'kategori', 'merek', 'harga', 'biaya',
       'margin_keuntungan', 'order_id', 'customer_id', 'jumlah',
       'tanggal_order', 'status', 'revenue', 'nama_lengkap', 'umur',
       'jenis_kelamin', 'email', 'kota', 'segmen_pelanggan', 'tanggal_daftar'],
      dtype='object')

In [ ]:
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])
today = pd.Timestamp.today()
df['tenure_hari'] = (today - df['tanggal_daftar']).dt.days
df

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,...,status,revenue,nama_lengkap,umur,jenis_kelamin,email,kota,segmen_pelanggan,tanggal_daftar,tenure_hari
0,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,458,30,1,...,Selesai,17.0,Dewi Santoso,35,P,dewi.santoso@gmail.com,Makassar,Standard,2023-01-27 11:53:41.526908635,1112
1,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,600,725,2,...,Selesai,34.0,Andi Santoso,38,L,andi.santoso@outlook.com,Jakarta,Basic,2024-10-23 11:26:39.499374216,477
2,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,621,508,1,...,Selesai,17.0,Budi Sari,41,P,budi.sari@outlook.com,Bandung,Standard,2024-04-08 05:11:47.384230288,675
3,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,672,17,1,...,Dibatalkan,17.0,Dewi Santoso,20,P,dewi.santoso@yahoo.com,Jakarta,Standard,2023-01-15 14:50:18.773466833,1123
4,1,Produk_1,Rumah Tangga,MerekC,17.0,8.0,52.94,939,389,3,...,Selesai,51.0,Andi Nugroho,51,P,andi.nugroho@gmail.com,Medan,Standard,2023-12-21 11:50:05.256570712,784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1416,601,3,...,Selesai,54.0,Rizki Sari,23,L,rizki.sari@gmail.com,Makassar,Standard,2024-07-02 04:26:44.005006256,590
1996,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1513,17,4,...,Selesai,72.0,Dewi Santoso,20,P,dewi.santoso@yahoo.com,Jakarta,Standard,2023-01-15 14:50:18.773466833,1123
1997,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1607,471,2,...,Selesai,36.0,Rizki Kusuma,41,P,rizki.kusuma@gmail.com,Medan,Premium,2024-03-05 09:52:56.470588232,709
1998,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1789,460,1,...,Selesai,18.0,Budi Putri,40,L,budi.putri@perusahaan.com,Medan,Premium,2024-02-24 08:40:51.063829784,719
1999,150,Produk_150,Buku,MerekC,18.0,8.0,55.56,1920,595,1,...,Selesai,18.0,Dewi Kusuma,43,P,dewi.kusuma@perusahaan.com,Jakarta,Standard,2024-06-26 16:52:51.964956192,595

In [ ]:
df['tanggal_order'] = pd.to_datetime(df['tanggal_order'])
df = df.sort_values(['customer_id','tanggal_order'])
df['selisih_hari'] = (df.groupby('customer_id')['tanggal_order'].diff().dt.days)
avg_interval = (df.groupby('customer_id').agg(avg_hari_antar_order=('selisih_hari','mean')).reset_index())
df = pd.merge(df, avg_interval, on = 'customer_id', how='left')
df

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,...,nama_lengkap,umur,jenis_kelamin,email,kota,segmen_pelanggan,tanggal_daftar,tenure_hari,selisih_hari,avg_hari_antar_order
0,100,Produk_100,Rumah Tangga,MerekD,11.0,6.0,45.45,655,1,1,...,Doni Pratama,25,P,doni.pratama@yahoo.com,Surabaya,Premium,2023-01-01 00:00:00.000000000,1138,NaN,85.00
1,51,Produk_51,Buku,MerekA,30.0,15.0,50.00,1121,1,2,...,Doni Pratama,25,P,doni.pratama@yahoo.com,Surabaya,Premium,2023-01-01 00:00:00.000000000,1138,85.0,85.00
2,7,Produk_7,Pakaian,MerekC,7.0,4.0,42.86,81,2,1,...,Dewi Sari,33,L,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,NaN,89.00
3,31,Produk_31,Kecantikan,MerekE,9.0,5.0,44.44,1050,2,2,...,Dewi Sari,33,L,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,176.0,89.00
4,89,Produk_89,Pakaian,MerekB,20.0,10.0,50.00,1111,2,1,...,Dewi Sari,33,L,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,11.0,89.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,21,Produk_21,Kecantikan,MerekB,27.0,12.0,55.56,1381,798,2,...,Doni Pratama,43,L,doni.pratama@yahoo.com,Medan,Basic,2024-12-29 04:08:42.653316640,410,20.0,62.25
1996,135,Produk_135,Rumah Tangga,MerekE,13.0,6.0,53.85,1961,798,2,...,Doni Pratama,43,L,doni.pratama@yahoo.com,Medan,Basic,2024-12-29 04:08:42.653316640,410,105.0,62.25
1997,44,Produk_44,Rumah Tangga,MerekE,20.0,10.0,50.00,155,799,1,...,Andi Pratama,62,L,andi.pratama@outlook.com,Makassar,Standard,2024-12-30 02:04:21.326658320,409,NaN,290.00
1998,68,Produk_68,Elektronik,MerekD,35.0,16.0,54.29,1748,799,3,...,Andi Pratama,62,L,andi.pratama@outlook.com,Makassar,Standard,2024-12-30 02:04:21.326658320,409,290.0,290.00
1999,103,Produk_103,Olahraga,MerekC,12.0,8.0,33.33,1118,800,3,...,Budi Putri,47,L,budi.putri@perusahaan.com,Medan,Standard,2024-12-31 00:00:00.000000000,408,NaN,NaN

In [ ]:
df['hari_order'] = df['tanggal_order'].dt.day_name()
freq = (df.groupby(['customer_id','hari_order']).size().reset_index(name='jumlah'))
idx = freq.groupby('customer_id')['jumlah'].idxmax()
fav_day = freq.loc[idx][['customer_id','hari_order']]
fav_day = fav_day.rename(columns={'hari_order':'hari_favorit'})
df = pd.merge(df,fav_day, on='customer_id', how='left')
df

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,...,jenis_kelamin,email,kota,segmen_pelanggan,tanggal_daftar,tenure_hari,selisih_hari,avg_hari_antar_order,hari_order,hari_favorit
0,100,Produk_100,Rumah Tangga,MerekD,11.0,6.0,45.45,655,1,1,...,P,doni.pratama@yahoo.com,Surabaya,Premium,2023-01-01 00:00:00.000000000,1138,NaN,85.00,Monday,Monday
1,51,Produk_51,Buku,MerekA,30.0,15.0,50.00,1121,1,2,...,P,doni.pratama@yahoo.com,Surabaya,Premium,2023-01-01 00:00:00.000000000,1138,85.0,85.00,Tuesday,Monday
2,7,Produk_7,Pakaian,MerekC,7.0,4.0,42.86,81,2,1,...,L,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,NaN,89.00,Monday,Wednesday
3,31,Produk_31,Kecantikan,MerekE,9.0,5.0,44.44,1050,2,2,...,L,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,176.0,89.00,Wednesday,Wednesday
4,89,Produk_89,Pakaian,MerekB,20.0,10.0,50.00,1111,2,1,...,L,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,11.0,89.00,Sunday,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,21,Produk_21,Kecantikan,MerekB,27.0,12.0,55.56,1381,798,2,...,L,doni.pratama@yahoo.com,Medan,Basic,2024-12-29 04:08:42.653316640,410,20.0,62.25,Sunday,Monday
1996,135,Produk_135,Rumah Tangga,MerekE,13.0,6.0,53.85,1961,798,2,...,L,doni.pratama@yahoo.com,Medan,Basic,2024-12-29 04:08:42.653316640,410,105.0,62.25,Monday,Monday
1997,44,Produk_44,Rumah Tangga,MerekE,20.0,10.0,50.00,155,799,1,...,L,andi.pratama@outlook.com,Makassar,Standard,2024-12-30 02:04:21.326658320,409,NaN,290.00,Monday,Monday
1998,68,Produk_68,Elektronik,MerekD,35.0,16.0,54.29,1748,799,3,...,L,andi.pratama@outlook.com,Makassar,Standard,2024-12-30 02:04:21.326658320,409,290.0,290.00,Thursday,Monday
1999,103,Produk_103,Olahraga,MerekC,12.0,8.0,33.33,1118,800,3,...,L,budi.putri@perusahaan.com,Medan,Standard,2024-12-31 00:00:00.000000000,408,NaN,NaN,Monday,Monday

In [ ]:
total_spend = (df.groupby('customer_id')['revenue'].sum().reset_index())
total_spend['tier'] = pd.qcut(total_spend['revenue'],q=3,labels=['Low','Medium','High'])
df = pd.merge(df,total_spend[['customer_id','tier']], on = 'customer_id', how ='left')
df

,product_id,nama_produk,kategori,merek,harga,biaya,margin_keuntungan,order_id,customer_id,jumlah,...,email,kota,segmen_pelanggan,tanggal_daftar,tenure_hari,selisih_hari,avg_hari_antar_order,hari_order,hari_favorit,tier
0,100,Produk_100,Rumah Tangga,MerekD,11.0,6.0,45.45,655,1,1,...,doni.pratama@yahoo.com,Surabaya,Premium,2023-01-01 00:00:00.000000000,1138,NaN,85.00,Monday,Monday,Medium
1,51,Produk_51,Buku,MerekA,30.0,15.0,50.00,1121,1,2,...,doni.pratama@yahoo.com,Surabaya,Premium,2023-01-01 00:00:00.000000000,1138,85.0,85.00,Tuesday,Monday,Medium
2,7,Produk_7,Pakaian,MerekC,7.0,4.0,42.86,81,2,1,...,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,NaN,89.00,Monday,Wednesday,Medium
3,31,Produk_31,Kecantikan,MerekE,9.0,5.0,44.44,1050,2,2,...,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,176.0,89.00,Wednesday,Wednesday,Medium
4,89,Produk_89,Pakaian,MerekB,20.0,10.0,50.00,1111,2,1,...,dewi.sari@yahoo.com,Jakarta,Basic,2023-01-01 21:55:38.673341677,1137,11.0,89.00,Sunday,Wednesday,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,21,Produk_21,Kecantikan,MerekB,27.0,12.0,55.56,1381,798,2,...,doni.pratama@yahoo.com,Medan,Basic,2024-12-29 04:08:42.653316640,410,20.0,62.25,Sunday,Monday,High
1996,135,Produk_135,Rumah Tangga,MerekE,13.0,6.0,53.85,1961,798,2,...,doni.pratama@yahoo.com,Medan,Basic,2024-12-29 04:08:42.653316640,410,105.0,62.25,Monday,Monday,High
1997,44,Produk_44,Rumah Tangga,MerekE,20.0,10.0,50.00,155,799,1,...,andi.pratama@outlook.com,Makassar,Standard,2024-12-30 02:04:21.326658320,409,NaN,290.00,Monday,Monday,Medium
1998,68,Produk_68,Elektronik,MerekD,35.0,16.0,54.29,1748,799,3,...,andi.pratama@outlook.com,Makassar,Standard,2024-12-30 02:04:21.326658320,409,290.0,290.00,Thursday,Monday,Medium
1999,103,Produk_103,Olahraga,MerekC,12.0,8.0,33.33,1118,800,3,...,budi.putri@perusahaan.com,Medan,Standard,2024-12-31 00:00:00.000000000,408,NaN,NaN,Monday,Monday,Low

In [ ]:
kota_encoding = pd.get_dummies(df['kota'],prefix = 'kota').astype(int)
kota_encoding

,kota_Bandung,kota_Jakarta,kota_Makassar,kota_Medan,kota_Semarang,kota_Surabaya
0,0,0,0,0,0,1
1,0,0,0,0,0,1
2,0,1,0,0,0,0
3,0,1,0,0,0,0
4,0,1,0,0,0,0
...,...,...,...,...,...,...
1995,0,0,0,1,0,0
1996,0,0,0,1,0,0
1997,0,0,1,0,0,0
1998,0,0,1,0,0,0
1999,0,0,0,1,0,0

In [ ]:
print("Contoh fitur perilaku pelanggan:")
cols = [
    'customer_id',
    'tenure_hari',
    'avg_hari_antar_order',
    'hari_favorit',
    'tier'
]
print(df[cols].drop_duplicates().head())

Contoh fitur perilaku pelanggan:
    customer_id  tenure_hari  avg_hari_antar_order hari_favorit    tier
0             1         1138                  85.0       Monday  Medium
2             2         1137                  89.0    Wednesday  Medium
6             3         1136                   NaN       Monday     Low
7             4         1135                  34.5     Thursday    High
10            5         1134                   NaN      Tuesday     Low