# Hands On

## 0. Notebook Preparation

In [ ]:
import pandas as pd

# Orders
orders = pd.DataFrame({
    "order_id": ["A001","A002","A003","A004","A005","A006","A007","A008"],
    "order_date": ["2024-01-02","2024-01-03","2024-01-03","2024-01-04",
                   "2024-01-05","2024-02-01","2024-02-02","2024-02-02"],
    "city": ["Jakarta","Bandung","Jakarta","Surabaya","Jakarta","Medan","Denpasar","Bandung"],
    "category": ["Food","Food","Beverage","NonFood","Food","Food","Beverage","NonFood"],
    "qty": [2,1,3,1,5,4,2,1],
    "price": [30000,25000,12000,75000,28000,15000,12000,70000],
    "customer_id": [101,102,101,103,104,105,106,102],
    "product_id": [1,1,2,3,1,1,2,3]
})

# Customers
customers = pd.DataFrame({
    "customer_id":[101,102,103,104,105,106],
    "customer_name":["Ani","Bima","Cici","Doni","Eka","Fahri"],
    "city":["Jakarta","Bandung","Surabaya","Jakarta","Medan","Denpasar"]
})

# Products
products = pd.DataFrame({
    "product_id":[1,2,3],
    "product_name":["Nasi Box","Teh Botol","Paket Starter"],
    "base_price":[25000,10000,70000],
    "product_category":["Food","Beverage","NonFood"]
})

orders

,order_id,order_date,city,category,qty,price,customer_id,product_id
0,A001,2024-01-02,Jakarta,Food,2,30000,101,1
1,A002,2024-01-03,Bandung,Food,1,25000,102,1
2,A003,2024-01-03,Jakarta,Beverage,3,12000,101,2
3,A004,2024-01-04,Surabaya,NonFood,1,75000,103,3
4,A005,2024-01-05,Jakarta,Food,5,28000,104,1
5,A006,2024-02-01,Medan,Food,4,15000,105,1
6,A007,2024-02-02,Denpasar,Beverage,2,12000,106,2
7,A008,2024-02-02,Bandung,NonFood,1,70000,102,3

In [ ]:
customers

   customer_id customer_name      city
0          101           Ani   Jakarta
1          102          Bima   Bandung
2          103          Cici  Surabaya
3          104          Doni   Jakarta
4          105           Eka     Medan
5          106         Fahri  Denpasar

In [ ]:
products

   product_id   product_name  base_price product_category
0           1       Nasi Box       25000             Food
1           2      Teh Botol       10000         Beverage
2           3  Paket Starter       70000          NonFood

## 1. Introduction to Pandas
- Filter
- DataFrame
- Selecting rows & columns

### 1.1 Ambil kolom & baris dasar
Menggunakan tabel Orders, tampilkan hanya kolom `order_id`, `city`, `qty`, `price` untuk **3 baris pertama**.

In [ ]:
# Tulis di sini
orders[['order_id', 'city', 'qty', 'price']].head(3)

NameError: name 'orders' is not defined

### 1.2 Filter baris dengan kondisi sederhana
Menggunakan tabel Orders, ambil baris **kota = "Jakarta"** dan **qty ≥ 3**.

In [ ]:
# Tulis di sini
orders.loc[(orders['city']=='Jakarta') & (orders['qty']>=3)]

### 1.3 Menambah kolom baru (metrik)
Tambahkan kolom `amount = qty * price`, lalu tampilkan `order_id`, `city`, `amount`.

In [ ]:
# Tulis di sini
orders['amount'] = orders['qty'] * orders['price']
orders[['order_id', 'city', 'amount']]

NameError: name 'orders' is not defined

In [ ]:
orders = orders.assign(amount = orders["qty"] * orders["price"])
orders[["order_id", "city", "amount"]]

NameError: name 'orders' is not defined

### 1.4 Filter multi-kondisi + pilih kolom dengan `.loc`
Ambil transaksi **kota** di `["Jakarta","Bandung"]` dengan `qty` antara **2–5**, tampilkan kolom `order_id, city, qty, price, amount` dan urutkan `qty` menurun.

In [ ]:
mask = orders["city"].isin(["Jakarta", "Bandung"]) & orders["qty"].between(2, 5)
mask

In [ ]:
result = (
    orders.loc[mask, ["order_id", "city", "qty", "price", "amount"]].sort_values("qty", ascending=False)
)
result

In [ ]:
# Tulis di sini
df = orders.loc[(orders['city'].isin(['Jakarta','Bandung'])) & (orders['qty'].between(2,5))]

df[['order_id', 'city', 'qty', 'price', 'amount']].sort_values('qty', ascending=False)

NameError: name 'orders' is not defined

## 2. Group by, Join, dan Merge Data

### 2.1 GroupBy agregasi
Hitung **total `amount` per `city`**, urutkan dari terbesar.

In [ ]:
# Tulis di sini
(orders.groupby("city", as_index=False)["amount"].sum()
        .rename(columns={"amount": "total_sales"})
        .sort_values("total_sales", ascending=False)
)

       city  total_sales
2   Jakarta       236000
0   Bandung        95000
4  Surabaya        75000
3     Medan        60000
1  Denpasar        24000

### 2.2 Join (index-based) untuk lookup
Buat lookup **region per city**, lalu join ke `orders` (left join by index):
- Jakarta/Bandung/Surabaya → Jawa
- Medan → Sumatra
- Denpasar → Bali

In [ ]:
# Tulis di sini
city_lookup = pd.DataFrame({
    "city": ["Jakarta", "Bandung", "Surabaya", "Medan", "Denpasar"],
    "region": ["Jawa", "Jawa", "Jawa", "Sumatra", "Bali"]
}).set_index("city")

city_lookup

           region
city
Jakarta      Jawa
Bandung      Jawa
Surabaya     Jawa
Medan     Sumatra
Denpasar     Bali

In [ ]:
orders.join(city_lookup, on="city")

,order_id,order_date,city,category,qty,price,customer_id,product_id,amount,region
0,A001,2024-01-02,Jakarta,Food,2,30000,101,1,60000,Jawa
1,A002,2024-01-03,Bandung,Food,1,25000,102,1,25000,Jawa
2,A003,2024-01-03,Jakarta,Beverage,3,12000,101,2,36000,Jawa
3,A004,2024-01-04,Surabaya,NonFood,1,75000,103,3,75000,Jawa
4,A005,2024-01-05,Jakarta,Food,5,28000,104,1,140000,Jawa
5,A006,2024-02-01,Medan,Food,4,15000,105,1,60000,Sumatra
6,A007,2024-02-02,Denpasar,Beverage,2,12000,106,2,24000,Bali
7,A008,2024-02-02,Bandung,NonFood,1,70000,102,3,70000,Jawa

### 2.3 Merge (column-based) dengan Products
Gabungkan `orders` dengan `products` untuk mendapatkan product_name. Tampilkan `order_id`, `product_name`, `product_category`, `amount`.

In [ ]:
orders.head(3)

,order_id,order_date,city,category,qty,price,customer_id,product_id,amount
0,A001,2024-01-02,Jakarta,Food,2,30000,101,1,60000
1,A002,2024-01-03,Bandung,Food,1,25000,102,1,25000
2,A003,2024-01-03,Jakarta,Beverage,3,12000,101,2,36000

In [ ]:
products.head(3)

   product_id   product_name  base_price product_category
0           1       Nasi Box       25000             Food
1           2      Teh Botol       10000         Beverage
2           3  Paket Starter       70000          NonFood

In [ ]:
# Tulis di sini
orders_prd = pd.merge(orders,
         products[["product_id", "product_name", "product_category"]],
         on="product_id",
         how="left"
         )
orders_prd[["order_id", "product_name", "product_category", "amount"]]

  order_id   product_name product_category  amount
0     A001       Nasi Box             Food   60000
1     A002       Nasi Box             Food   25000
2     A003      Teh Botol         Beverage   36000
3     A004  Paket Starter          NonFood   75000
4     A005       Nasi Box             Food  140000
5     A006       Nasi Box             Food   60000
6     A007      Teh Botol         Beverage   24000
7     A008  Paket Starter          NonFood   70000

### 2.4 Merge ke customers lalu cari top customer per city
Gabungkan `orders` ↔ `customers` pada `customer_id`, hitung total `amount` per (city, customer_name), lalu ambil 1 customer teratas per kota.

In [ ]:
# Tulis di sini
orders_cust = pd.merge(
    orders, customers[["customer_id", "customer_name", "city"]]
    .rename(columns={"city": "customer_city"}),
    on="customer_id", how="left"
)

city_customer_sales = orders_cust.groupby(["city", "customer_name"], as_index=False)["amount"].sum().sort_values(["city", "amount"], ascending=[True, False])

top_per_city = city_customer_sales.groupby("city", as_index=False).head(1)
top_per_city

       city customer_name  amount
0   Bandung          Bima   95000
1  Denpasar         Fahri   24000
3   Jakarta          Doni  140000
4     Medan           Eka   60000
5  Surabaya          Cici   75000

## 3. Datetime

### 3.1 Konversi tanggal & komponen
Ubah `order_date` jadi datetime; buat kolom `year`, `month`, dan `day_name`.

In [ ]:
# Tulis di sini
orders["order_date"] = pd.to_datetime(orders["order_date"])

orders["year"] = orders["order_date"].dt.year
orders["month"] = orders["order_date"].dt.month
orders["day_name"] = orders["order_date"].dt.day_name()

orders[["order_id", "order_date", "year", "month", "day_name"]]

  order_id order_date  year  month   day_name
0     A001 2024-01-02  2024      1    Tuesday
1     A002 2024-01-03  2024      1  Wednesday
2     A003 2024-01-03  2024      1  Wednesday
3     A004 2024-01-04  2024      1   Thursday
4     A005 2024-01-05  2024      1     Friday
5     A006 2024-02-01  2024      2   Thursday
6     A007 2024-02-02  2024      2     Friday
7     A008 2024-02-02  2024      2     Friday

### 3.2 Filter range tanggal
Ambil transaksi dari **2024-02-01 s/d 2024-02-02**.

In [ ]:
# Tulis di sini
mask = (orders["order_date"] >= "2024-02-01") & (orders["order_date"] <= "2024-02-02")
orders.loc[mask, ["order_id", "order_date", "city", "amount"]]

  order_id order_date      city  amount
5     A006 2024-02-01     Medan   60000
6     A007 2024-02-02  Denpasar   24000
7     A008 2024-02-02   Bandung   70000

### 3.3 Monthly sales dengan resampling
Jadikan `order_date` sebagai index dan hitung total `amount` per bulan, sekaligus jumlah order per bulan.

In [ ]:
orders

,order_id,order_date,city,category,qty,price,customer_id,product_id,amount,year,month,day_name
0,A001,2024-01-02,Jakarta,Food,2,30000,101,1,60000,2024,1,Tuesday
1,A002,2024-01-03,Bandung,Food,1,25000,102,1,25000,2024,1,Wednesday
2,A003,2024-01-03,Jakarta,Beverage,3,12000,101,2,36000,2024,1,Wednesday
3,A004,2024-01-04,Surabaya,NonFood,1,75000,103,3,75000,2024,1,Thursday
4,A005,2024-01-05,Jakarta,Food,5,28000,104,1,140000,2024,1,Friday
5,A006,2024-02-01,Medan,Food,4,15000,105,1,60000,2024,2,Thursday
6,A007,2024-02-02,Denpasar,Beverage,2,12000,106,2,24000,2024,2,Friday
7,A008,2024-02-02,Bandung,NonFood,1,70000,102,3,70000,2024,2,Friday

In [ ]:
# Tulis di sini
orders_dt = orders.copy()
orders_dt["amount"] = orders_dt["qty"] * orders_dt ["price"]
orders_dt = orders_dt.set_index("order_date")

monthly = (orders_dt
           .resample("ME")    # ME --> month end; MS --> month start
            .agg(total_amonut=("amount", "sum"),
                 order_count=("order_id", "count"))
            .reset_index()
)
monthly

  order_date  total_amonut  order_count
0 2024-01-31        336000            5
1 2024-02-29        154000            3

## 4. Data Manipulation Process

### 4.1 Cek tipe, missing, duplikat
- Tampilkan `dtypes`
- Cek jumlah missing per kolom
- Pastikan `order_id` unik (drop dupe kalau ada)

In [ ]:
# Tulis di sini
print(orders.isna().sum())

orders = orders.drop_duplicates(subset=["order_id"])

order_id       0
order_date     0
city           0
category       0
qty            0
price          0
customer_id    0
product_id     0
amount         0
year           0
month          0
day_name       0
dtype: int64

### 4.2 “View” data untuk stakeholder
Buat view sederhana **Jakarta/Bandung** saja, kolom: `order_id`, `order_date`, `city`, `qty`, `price`, `amount`, urutkan `amount` desc.

In [ ]:
# Tulis di sini
view = (orders.loc[orders["city"].isin(["Jakarta", "Bandung"]),
                          ["order_id", "order_date", "city", "qty", "price", "amount"]]
        .sort_values("amount", ascending=False)
        )
view

  order_id order_date     city  qty  price  amount
4     A005 2024-01-05  Jakarta    5  28000  140000
7     A008 2024-02-02  Bandung    1  70000   70000
0     A001 2024-01-02  Jakarta    2  30000   60000
2     A003 2024-01-03  Jakarta    3  12000   36000
1     A002 2024-01-03  Bandung    1  25000   25000

### 4.3 Mini pipeline daily sales + cumulative sum
Buat tabel harian berisi `date`, `daily_amount`, dan `cum_amount` (akumulasi dari awal waktu). Kerjakan dalam satu rangkaian operasi (method chaining).

In [ ]:
# Tulis di sini
## order_date --> pd.Datetime
## amount --> qty * price
## date --> order_date.dt.date

## .groupby("date")
## agg amount --> sum
## sort_values date, ascending = True

## assign cumulative_amount --> .cumsum()

## 5. Data Transformation

### 5.1 Rename, flag, dan sort
- Rename `category` → `product_category`
- Buat `is_high_value` (amount ≥ 50_000)
- Urutkan `order_date` naik

In [ ]:
# Tulis di sini
orders = orders.rename(columns={"category": "product_category"})
orders["is_high_values"] = orders["amount"] >= 50_000
orders.sort_values("order_date")

,order_id,order_date,city,product_category,qty,price,customer_id,product_id,amount,year,month,day_name,is_high_values
0,A001,2024-01-02,Jakarta,Food,2,30000,101,1,60000,2024,1,Tuesday,True
1,A002,2024-01-03,Bandung,Food,1,25000,102,1,25000,2024,1,Wednesday,False
2,A003,2024-01-03,Jakarta,Beverage,3,12000,101,2,36000,2024,1,Wednesday,False
3,A004,2024-01-04,Surabaya,NonFood,1,75000,103,3,75000,2024,1,Thursday,True
4,A005,2024-01-05,Jakarta,Food,5,28000,104,1,140000,2024,1,Friday,True
5,A006,2024-02-01,Medan,Food,4,15000,105,1,60000,2024,2,Thursday,True
6,A007,2024-02-02,Denpasar,Beverage,2,12000,106,2,24000,2024,2,Friday,False
7,A008,2024-02-02,Bandung,NonFood,1,70000,102,3,70000,2024,2,Friday,True

### 5.2 Pivot mini (agregasi by month x city)
Buat pivot total amount per `month` (baris) × `city` (kolom).

In [ ]:
# Tulis di sini
pivot_amt = (orders.pivot_table(index="month", columns="city", values="amount", aggfunc="count", fill_value=0))
pivot_amt

city   Bandung  Denpasar  Jakarta  Medan  Surabaya
month
1            1         0        3      0         1
2            1         1        0      1         0

### 5.3 Pivot month × category + row-share
Buat pivot total `amount` dengan baris = `month`, kolom = `product_category`, lalu tambahkan tabel kedua berisi proporsi per baris (tiap baris dijadikan persentase 0–1).

In [ ]:
# Tulis di sini
pivot_amt = (orders.pivot_table(index="month", columns="product_category", values="amount", aggfunc="sum", fill_value=0))
pivot_amt

## 6. Feature Engineering

### 6.1 Label Encoding sederhana
Buat peta untuk `product_category`: `{"Food":0,"Beverage":1,"NonFood":2}` → kolom `cat_le`.

In [ ]:
# Tulis di sini
cat_map = {"Food": 0, "Beverage": 1, "NonFood": 2}
orders["cat_le"] = orders["product_category"].map(cat_map)
orders[["order_id", "product_category", "cat_le"]]

  order_id product_category  cat_le
0     A001             Food       0
1     A002             Food       0
2     A003         Beverage       1
3     A004          NonFood       2
4     A005             Food       0
5     A006             Food       0
6     A007         Beverage       1
7     A008          NonFood       2

### 6.2 One-Hot Encoding `city` dan binning `price`
- OHE city → kolom `city_...`
- Binning `price` ke low/mid/high (≤15k, 15k–30k, >30k) → price_bucket

In [ ]:
# Tulis di sini
city_ohe = pd.get_dummies(orders["city"], prefix="city")
orders_fe = pd.concat([orders, city_ohe], axis=1)

orders_fe["price_bucket"] = pd.cut(
    orders_fe["price"],
    bins=[0, 15_000, 30_000, float("inf")],
    labels=["low", "mid", "high"],
    right=True
)
orders_fe[["order_id", "city", "price", "price_bucket"] + list(city_ohe.columns)]

,order_id,city,price,price_bucket,city_Bandung,city_Denpasar,city_Jakarta,city_Medan,city_Surabaya
0,A001,Jakarta,30000,mid,False,False,True,False,False
1,A002,Bandung,25000,mid,True,False,False,False,False
2,A003,Jakarta,12000,low,False,False,True,False,False
3,A004,Surabaya,75000,high,False,False,False,False,True
4,A005,Jakarta,28000,mid,False,False,True,False,False
5,A006,Medan,15000,low,False,False,False,True,False
6,A007,Denpasar,12000,low,False,True,False,False,False
7,A008,Bandung,70000,high,True,False,False,False,False

### 6.3 Target mean encoding sederhana untuk kategori
Hitung rata-rata `amount` per `product_category`, lalu map kembali ke setiap baris sebagai kolom `cat_mean_amount`.

In [ ]:
# Tulis di sini
cat_mean_amount = orders.groupby("product_category")["amount"].mean().to_dict()
orders["cat_mean_amount"] = orders["product_category"].map(cat_mean_amount)
orders

---

#### Made by **Mario Caesar** (https://linktr.ee/caesarmario_) w/ 💖